import test from 'node:test';
import assert from 'node:assert/strict';
import {OpsStore} from './ops-store.mjs';
import {OpsIntegrations} from './ops-integrations.mjs';
const now=()=>new Date('2026-10-08T12:00:00Z');
const env={OPS_JIRA_ENABLED:'true',OPS_JIRA_BASE_URL:'https://test.atlassian.net',OPS_JIRA_PROJECT:'OPS',OPS_JIRA_EMAIL:'stub@example.invalid',OPS_JIRA_TOKEN:'stub-secret',OPS_DATADOG_ENABLED:'true',OPS_DATADOG_API_KEY:'stub-datadog'};
test('unconfigured SaaS remains honest local/off and never invokes fetch',async()=>{
  const store=new OpsStore({now});try{const item=store.receive(store.samples().conflict).case;let requests=0;const adapters=new OpsIntegrations(store,{env:{},fetchImpl:async()=>{requests++;throw new Error('must not send');}});await adapters.deliver(item.id);assert.equal(requests,0);assert.equal(adapters.status().find(i=>i.id==='jira').mode,'local');assert.equal(adapters.status().find(i=>i.id==='datadog').mode,'off');assert.equal(store.rows('tickets')[0].mode,'local');await assert.rejects(()=>adapters.retry(item.id),error=>error.status===409);}finally{store.close();}
});
test('opt in adapters deliver only synthetic task metadata/counts, and failure/retry preserves product',async()=>{
  const store=new OpsStore({now});try{const item=store.receive(store.samples().conflict).case;const before=store.rows('products');let online=false,requests=[];const adapters=new OpsIntegrations(store,{env,fetchImpl:async(url,options)=>{requests.push({url,options});if(!online)throw new Error('stub offline');return {ok:true,json:async()=>({key:'OPS-100'})};}});assert.equal(adapters.status().find(i=>i.id==='jira').mode,'configured');await adapters.deliver(item.id);assert.deepEqual(store.rows('products'),before);assert.equal(adapters.status().find(i=>i.id==='jira').mode,'failed');assert.equal(adapters.status().find(i=>i.id==='datadog').mode,'failed');online=true;await adapters.retry(item.id);assert.equal(store.rows('tickets')[0].mode,'jira');assert.equal(store.rows('tickets')[0].externalUrl,'https://test.atlassian.net/browse/OPS-100');assert.equal(adapters.status().find(i=>i.id==='jira').mode,'connected');assert.equal(adapters.status().find(i=>i.id==='datadog').mode,'connected');assert.deepEqual(store.rows('products'),before);for(const {options} of requests){assert.ok(!options.body.includes(item.sourceText));assert.ok(!options.body.includes('rate=3.76'));}assert.ok(!JSON.stringify(adapters.status()).includes('stub-secret'));const count=requests.length;await adapters.deliver(item.id);assert.equal(requests.length,count+1,'existing Jira issue is not recreated; only metrics sent');}finally{store.close();}
});
test('late external response after reset cannot restore deleted tickets, cases or events',async()=>{
  const store=new OpsStore({now});try{const item=store.receive(store.samples().conflict).case;let finish;const adapters=new OpsIntegrations(store,{env:{...env,OPS_DATADOG_ENABLED:'false'},fetchImpl:async()=>new Promise(resolve=>{finish=()=>resolve({ok:true,json:async()=>({key:'OPS-10'})});})});const task=adapters.deliver(item.id);store.reset({scope:'synthetic-demo'});finish();await task;assert.equal(store.state().cases.length,0);assert.equal(store.rows('tickets').length,0);assert.equal(store.rows('events').length,0);assert.equal(store.get('products','P1').version,1);}finally{store.close();}
});
test('parallel delivery calls share one external request per case',async()=>{
  const store=new OpsStore({now});try{const item=store.receive(store.samples().conflict).case;let finish,requests=0;const adapters=new OpsIntegrations(store,{env:{...env,OPS_DATADOG_ENABLED:'false'},fetchImpl:async()=>{requests++;return new Promise(resolve=>{finish=()=>resolve({ok:true,json:async()=>({key:'OPS-11'})});});}});const a=adapters.deliver(item.id),b=adapters.deliver(item.id);finish();await Promise.all([a,b]);assert.equal(requests,1);}finally{store.close();}
});
