import {renderOpsMap} from './ops-map.mjs';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const labels={pending:'검토 대기',applied:'반영 완료',held:'보류',conflict:'다시 확인',scheduled:'적용 예정',research:'조사 기록'};
const fields={rate:'상품 표시 금리',limit:'한도',reviewId:'심의필',active:'판매 상태'};
const num=value=>Number(value).toLocaleString('ko-KR',{maximumFractionDigits:2});
const valueText=(field,value)=>value===undefined?'—':field==='rate'?num(value)+'%':field==='limit'?num(value/10000)+'만원':field==='active'?(value?'판매 중':'판매 중지'):String(value);
const shortNotice=value=>{const t=String(value||'');const names=[['ai-normal-','정상 금리'],['ai-conditional-','고객 조건'],['ai-missing-date-','날짜 누락'],['ai-conflict-','금리 충돌'],['ai-future-','미래 적용'],['ai-competitor-','경쟁상품']];const name=names.find(([prefix])=>t.startsWith(prefix));return name?name[1]:'이전 공지 · '+t.slice(-7);};
let state=null,selectedId=null,inputSample=null,lastReceipt=null,oldReview=null,busy=false,resultMessage=null,modelStatus=null,selectedQuote=null,lastSignature='';
let analyzing=false,analysisSource='',analysisError=null;
async function api(path,body){
 const response=await fetch('/api/ops/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Ops-Client':'local-demo'},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const data=await response.json();if(!response.ok){const e=new Error(data.error||data.reason||'요청을 처리하지 못했습니다.');e.status=response.status;throw e;}return data;
}
function activeCase(){return state?.cases.find(c=>c.id===selectedId)||null;}
function setBusy(value){busy=value;for(const id of ['ops-submit','ops-refresh','ops-reset','ops-sample','ops-source','ops-map-normal','ops-map-held','ops-map-new'])$(id).disabled=value;$('ops-duplicate').disabled=value||!lastReceipt;document.querySelectorAll('#ops-review-detail button, #ops-review-detail textarea').forEach(el=>el.disabled=value||el.dataset.unavailable==='true');$('ops-submit').textContent=value?'처리 중…':'AI로 공지 읽기 →';}
async function action(run){if(busy)return;setBusy(true);try{await run();}catch(e){if(analyzing)analysisError=e.message;resultMessage={error:true,text:(e.status===409?'변경을 반영하지 않았어요. ':'')+e.message};$('ops-input-note').textContent=e.message;}finally{const checkedModel=analyzing;analyzing=false;if(checkedModel){try{await refreshModel();}catch{}}try{await refresh();}catch(e){$('ops-storage-label').textContent='서버 연결 실패';$('ops-review-detail').innerHTML='<div class="ops-error-banner">'+esc(e.message)+'<br>로컬 서버를 실행하고 새로 확인을 누르세요.</div>';}setBusy(false);}}
async function refresh(){const next=await api('state');if(state&&state.epoch!==next.epoch){oldReview=null;lastReceipt=null;selectedId=null;resultMessage=null;selectedQuote=null;analysisError=null;}state=next;if(!state.cases.some(c=>c.id===selectedId))selectedId=state.cases.at(-1)?.id||null;render();}
async function chooseSample(){const samples=await api('ai-samples');const sample=samples[$('ops-sample').value];if(!sample)throw new Error('샘플 공지를 준비하지 못했습니다.');inputSample=structuredClone(sample);$('ops-notice-label').textContent=shortNotice(sample.noticeId);$('ops-source').value=sample.sourceText;$('ops-compose').open=!activeCase();}
async function refreshModel(){modelStatus=await api('ai-status');$('ops-model-status').classList.toggle('unavailable',!modelStatus.connected);$('ops-model-status').innerHTML='<b>'+(modelStatus.connected?'● 실제 모델 연결됨':'○ 모델 연결 필요')+'</b><span>'+esc(modelStatus.model)+' · '+esc(modelStatus.provider)+'</span><small>'+esc(modelStatus.connected?'원문을 실제로 추론합니다. 샘플 응답 대체 없음.':modelStatus.error||'llm-local.ps1 실행 후 다시 확인하세요.')+'</small>';}
function render(){
 if(!state)return;$('ops-analysis-banner').hidden=!analyzing;const signature=JSON.stringify([state,selectedId,resultMessage,oldReview,selectedQuote,modelStatus,analyzing,analysisError]);if(signature===lastSignature)return;lastSignature=signature;
 const c=activeCase(),p=state.products.find(p=>p.id===c?.productId)||null;
 $('ops-storage-label').textContent='SQLite 저장 · 접수 '+state.cases.length+'건';$('ops-case-count').textContent=state.cases.length+'건';
 $('ops-case-list').innerHTML=state.cases.slice().reverse().map(c=>'<button class="ops-case-tab '+(c.id===selectedId?'active':'')+'" data-case-id="'+esc(c.id)+'" aria-pressed="'+(c.id===selectedId)+'">'+esc(shortNotice(c.noticeId))+' · r'+esc(c.sourceRevision)+' · '+(labels[c.status]||esc(c.status))+'</button>').join('');
 $('ops-case-list').querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{if(busy)return;selectedId=button.dataset.caseId;oldReview=null;selectedQuote=null;resultMessage=null;analysisError=null;render();}));
 renderFlow(c);renderOriginal(c);renderAI(c);renderValidation(c);renderReview(c,p);renderCustomer(c,p||state.products[0]);renderTickets();renderEvents();renderRoles();
 updateMap();
}
function updateMap(){const c=activeCase(),p=state?.products.find(p=>p.id===c?.productId)||state?.products[0];renderOpsMap({caseItem:c,product:p,busy:analyzing,modelStatus,draftSource:analysisSource,analysisError,onSelectStage:openMapStage});}
function openMapStage(stage){const selectors={source:'.ops-input',ai:'.ops-ai',validation:'.ops-validation',review:'.ops-review',output:'.ops-result-row',exceptions:'.ops-ticket-panel'};if(['source','ai','validation','output'].includes(stage))$('ops-inspection').open=true;const target=document.querySelector(selectors[stage]||'.ops-input');const heading=target?.querySelector('h2');target?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
async function showMapExample(kind){if(busy||!state)return;const c=state.cases.slice().reverse().find(c=>c.aiInterpretation&&(kind==='normal'?['pending','applied'].includes(c.status)&&c.aiInterpretation.checks.every(x=>x.status==='passed'):['held','conflict'].includes(c.status)));if(c){selectedId=c.id;oldReview=null;selectedQuote=null;resultMessage=null;analysisError=null;render();}else{await action(async()=>{$('ops-sample').value=kind==='normal'?'normal':'conditional';await chooseSample();$('ops-compose').open=true;$('ops-input-note').textContent='이 상황의 AI 분석 기록이 아직 없습니다. 공지를 읽어 검토안을 만드세요.';openMapStage('source');});}}
function renderFlow(c){
 const ai=c?.aiInterpretation,failed=ai?.checks.some(x=>x.status==='failed');
 const steps=[['01','원문',c?'complete':'',c?'접수한 원문을 보존':'한국어 공지 입력'],['02','AI가 읽은 내용',ai?'complete':'',ai?'변경값 + 근거 + 조건':'실제 모델이 읽기'],['03','검증 결과',failed?'failed':ai?'complete':'',failed?'확인이 필요한 내용 있음':'코드로 원문·값 대조'],['04','담당자 판단',c?.status==='pending'?'waiting':c?.status==='applied'?'complete':'',c?.status==='applied'?'승인 후 DB·고객 화면 반영':'승인 전에는 DB 유지']];
 $('ops-flow').innerHTML=steps.map(([n,title,cls,detail])=>'<div class="ops-flow-step '+cls+'"><small>STEP '+n+'</small><b>'+title+'</b><em>'+detail+'</em></div>').join('');
}
function renderOriginal(c){
 const el=$('ops-original');el.hidden=!c;if(!c)return;const src=c.sourceText,quote=selectedQuote,at=quote?src.indexOf(quote):-1;
 const sourceHTML=at<0?esc(src):esc(src.slice(0,at))+'<mark>'+esc(quote)+'</mark>'+esc(src.slice(at+quote.length));
 el.innerHTML='<div class="ops-source-heading">접수 원문 <span>r'+c.sourceRevision+'</span></div><pre>'+sourceHTML+'</pre><small>'+(quote?'선택한 AI 근거 문장을 원문에서 강조했습니다.':'AI의 근거 문장을 누르면 원문의 위치를 확인할 수 있어요.')+'</small>';
}
function renderAI(c){
 const el=$('ops-ai-detail'),a=c?.aiInterpretation;
 if(!a){el.innerHTML='<div class="ops-empty"><span>AI</span><h3>'+(c?'새 AI 분석이 필요해요.':'AI는 무엇을 읽을까?')+'</h3><p>'+(c?.sourceChannel==='llm'?'원문이 바뀌어 이전 AI 응답을 폐기했습니다. 오른쪽에서 다시 분석하세요.':c?'이 기록은 이전 규칙 추출 방식입니다. 왼쪽 한국어 공지를 AI로 읽어 새 검토 건을 만드세요.':'원문의 변경값과 적용 조건을 읽어 검토안을 만듭니다.')+'</p></div>';return;}
 el.innerHTML='<p class="ops-ai-summary">'+esc(a.summary)+'</p><div class="ops-model-receipt"><span>실제 모델 응답</span><small>'+esc(a.model)+' · '+(a.elapsedMs/1000).toFixed(1)+'초</small></div><div class="ops-ai-values">'+(a.changes.map((change,i)=>'<article class="ops-ai-value"><div><span>'+esc(fields[change.field]||change.field)+'</span><strong>'+esc(valueText(change.field,change.value))+'</strong></div><button class="ops-quote" data-quote-index="'+i+'" title="원문의 해당 문장 보기"><span>↖ 원문 근거</span>“'+esc(change.quote)+'”</button></article>').join('')||'<p class="ops-muted">변경값을 찾지 못했습니다.</p>')+'</div><div class="ops-ai-date"><span>적용일</span><b>'+esc(a.effectiveDate||'찾지 못함')+'</b>'+(a.dateQuote?'<button id="ops-date-quote" class="ops-text-button">원문 근거 보기 ↖</button>':'')+'</div><div class="ops-ai-conditions"><b>적용 조건</b><p>'+(a.conditions.length?a.conditions.map(esc).join('<br>'):'AI가 별도 제한 조건을 찾지 않았습니다.')+'</p></div><div class="ops-ai-questions '+(a.questions.length?'has-questions':'')+'"><b>확인할 질문</b><p>'+(a.questions.length?a.questions.map(esc).join('<br>'):'AI가 확인 질문을 남기지 않았습니다. 코드 검증은 별도로 수행합니다.')+'</p></div>';
 el.querySelectorAll('[data-quote-index]').forEach(button=>button.addEventListener('click',()=>{selectedQuote=a.changes[Number(button.dataset.quoteIndex)].quote;renderOriginal(c);button.classList.add('selected');const source=$('ops-original');source.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});}));
 $('ops-date-quote')?.addEventListener('click',()=>{selectedQuote=a.dateQuote;renderOriginal(c);});
}
function renderValidation(c){
 const a=c?.aiInterpretation;if(!a){$('ops-validation-detail').innerHTML='<div class="ops-empty"><span>✓</span><h3>AI 응답 뒤에 확인합니다.</h3><p>근거·수치·날짜·고객 범위·상품 버전을 코드로 검사합니다.</p></div>';return;}
 const failures=a.checks.filter(x=>x.status==='failed');
 $('ops-validation-detail').innerHTML='<div class="ops-check-summary '+(failures.length?'blocked':'')+'"><b>'+(failures.length?failures.length+'개 확인 필요':'검증 통과')+'</b><span>'+(failures.length?'승인을 열지 않고 검토할 일로 남깁니다.':'검증을 통과한 후보입니다. 최종 반영은 담당자가 결정합니다.')+'</span></div><div class="ops-checks">'+a.checks.map(x=>'<article class="ops-check '+x.status+'"><span aria-hidden="true">'+(x.status==='passed'?'✓':'!')+'</span><div><b>'+esc(x.label)+'</b><p>'+esc(x.detail)+'</p></div></article>').join('')+'</div><p class="ops-rule-note">이 결과는 모델의 자기 평가가 아니라 서버 코드의 검사 결과입니다. 단순 공지용 보수적인 규칙을 사용합니다.</p>';
}
function renderReview(c,p){
 if(!c){$('ops-review-detail').innerHTML='<div class="ops-empty"><span>↖</span><h3>공지 한 건부터 시작하세요</h3><p>상단의 ‘공지 입력·AI로 읽기’에서 원문을 준비하세요. 분석 뒤 변경 후보가 이곳에 나타납니다.</p></div>';return;}
 const dbChanged=c.status==='pending'&&c.expectedProductVersion!==p?.version,pending=c.status==='pending'&&!dbChanged,canRevise=['pending','held','conflict'].includes(c.status),isAI=c.sourceChannel==='llm',snapshot={sourceRevision:c.sourceRevision,expectedProductVersion:c.expectedProductVersion},before=c.before||p||{},changes=c.candidate?.changes||{};
 $('ops-review-detail').innerHTML='<div class="ops-case-top"><span class="ops-status '+esc(c.status)+'">'+(dbChanged?'DB 변경 · 재검토':labels[c.status]||esc(c.status))+'</span><small>'+esc(p?.id||c.productId)+'</small></div><h3 class="ops-review-title">'+esc(p?.bank||'가상 금융사')+'<br>'+esc(p?.name||'상품 확인 필요')+'</h3><p class="ops-reason">'+esc(dbChanged?'검토 기준 이후 상품 DB가 바뀌었습니다. 현재 원문을 다시 분석하세요.':pending?'원문 근거와 검사 결과를 확인하고 반영 여부를 결정하세요.':c.status==='applied'?'승인한 변경입니다. 지도와 고객 화면에서 현재 DB 값을 확인하세요.':c.reason)+'</p><table class="ops-changes"><thead><tr><th>항목</th><th>'+(c.status==='applied'?'변경 전':'검토 기준')+'</th><th>'+(c.status==='applied'?'승인값':'후보')+'</th></tr></thead><tbody>'+(Object.entries(changes).map(([k,v])=>'<tr><td>'+esc(fields[k]||k)+'</td><td>'+esc(valueText(k,before[k]))+'</td><td>'+esc(valueText(k,v))+'</td></tr>').join('')||'<tr><td colspan="3">새 AI 분석이 필요합니다.</td></tr>')+'</tbody></table><div class="ops-review-stamp"><span>원문 r'+c.sourceRevision+'</span><span>'+(c.expectedProductVersion==null?'조사 자료':'기준 DB v'+c.expectedProductVersion)+'</span></div><div class="ops-decision-buttons"><button id="ops-approve" class="primary" data-unavailable="'+!pending+'" '+(pending&&!busy?'':'disabled')+'>'+(c.status==='applied'?'반영 완료':'확인한 변경 승인')+'</button><button id="ops-hold" class="quiet" data-unavailable="'+!pending+'" '+(pending&&!busy?'':'disabled')+'>반영 보류</button></div>'+(canRevise?'<details class="ops-edit-revision"><summary>검토 중 원문 변경 시험</summary><label for="ops-revised-source">새 원문</label><textarea id="ops-revised-source">'+esc(c.sourceText)+'</textarea><button id="ops-revise" class="quiet">원문 변경 저장</button></details>':'')+(isAI&&canRevise?'<button id="ops-reanalyze" class="quiet full ops-reanalyze">현재 원문을 AI로 다시 읽기</button>':'')+(oldReview?.caseId===c.id?'<button id="ops-stale" class="ops-text-button">이전 검토로 승인 시도</button>':'')+'<p class="ops-rule-note">승인할 때 원문 버전·해시와 DB 버전을 다시 확인합니다.</p>'+(resultMessage?'<div class="ops-review-result '+(resultMessage.error?'error':'')+'" role="status">'+esc(resultMessage.text)+'</div>':'');
 $('ops-approve').addEventListener('click',()=>action(async()=>{const result=await api('cases/'+encodeURIComponent(c.id)+'/decision',{decision:'approve',...snapshot,decisionId:crypto.randomUUID(),actor:'demo-reviewer'});resultMessage={error:false,text:result.duplicate?'이미 처리된 승인입니다. 한 번만 반영했습니다.':'승인한 값을 저장했습니다. 아래 고객 화면도 같은 DB를 읽습니다.'};oldReview=null;await chooseSample();}));
 $('ops-hold').addEventListener('click',()=>action(async()=>{await api('cases/'+encodeURIComponent(c.id)+'/decision',{decision:'hold',...snapshot,decisionId:crypto.randomUUID(),actor:'demo-reviewer'});resultMessage={error:false,text:'반영을 보류하고 로컬 업무함에 남겼습니다.'};}));
 $('ops-revise')?.addEventListener('click',()=>action(async()=>{const changed=$('ops-revised-source').value;if(changed===c.sourceText)throw new Error('원문 내용을 바꾼 뒤 저장하세요.');oldReview={caseId:c.id,...snapshot};await api('cases/'+encodeURIComponent(c.id)+'/revise',{sourceText:changed});selectedQuote=null;resultMessage={error:false,text:'원문이 바뀌어 이전 AI 해석과 승인을 무효화했습니다. 다시 분석해야 합니다.'};}));
 $('ops-reanalyze')?.addEventListener('click',()=>action(async()=>{announceAnalysis(c.sourceText);await api('cases/'+encodeURIComponent(c.id)+'/reanalyze',{sourceRevision:c.sourceRevision});resultMessage={error:false,text:'새 원문을 실제 모델로 다시 읽고 검증했습니다.'};}));
 $('ops-stale')?.addEventListener('click',()=>action(async()=>{const captured=oldReview;await api('cases/'+encodeURIComponent(c.id)+'/decision',{decision:'approve',sourceRevision:captured.sourceRevision,expectedProductVersion:captured.expectedProductVersion,decisionId:crypto.randomUUID(),actor:'demo-reviewer'});resultMessage={error:true,text:'검수 필요: 이전 검토가 승인되었습니다.'};}));
}
function renderCustomer(c,p){
 if(!p)return;$('ops-customer-preview').innerHTML='<div class="ops-phone-head"><b>가상 금융쇼핑</b><span>DEMO</span></div><p class="ops-phone-label">'+esc(p.bank)+'</p><h3>'+esc(p.name)+'</h3><div class="ops-phone-rate">'+num(p.rate)+'<small>% · 상품 표시 정보</small></div><div class="ops-phone-meta">한도 <b>'+num(p.limit/10000)+'만원</b> · '+(p.active?'판매 중':'판매 중지')+'<br>'+esc(p.reviewId)+' · 상품 '+esc(p.id)+' · DB v'+p.version+'</div><div class="ops-phone-caption">합성 상품 정보 · 개인별 실제 심사 금리가 아닙니다.</div>';
 $('ops-output-note').textContent=c?.status==='applied'?'승인한 값을 DB v'+p.version+'에서 조회했습니다. 새로고침해도 유지됩니다.':'현재 DB v'+p.version+'. 검토 후보는 아직 고객 화면에 표시하지 않습니다.';
}
function renderTickets(){$('ops-ticket-list').innerHTML=state.tickets.length?state.tickets.slice(-4).reverse().map(t=>'<article class="ops-ticket-row"><div><b>'+esc(t.title)+'</b><p>'+esc(t.reason)+'</p></div><span class="ops-small-tag">로컬 업무함<br>'+esc(t.status)+'</span><small>'+esc(t.owner||'데모 운영 담당자')+' · '+esc(t.id)+'</small></article>').join(''):'<p class="ops-muted">조건이 모호하거나 근거가 빠지면 담당자가 확인할 일로 남습니다.</p>';}
function renderEvents(){$('ops-event-list').innerHTML=state.events.length?'<div class="ops-events">'+state.events.slice(-10).reverse().map(e=>'<div class="ops-event"><time>'+new Date(e.at).toLocaleTimeString('en-GB',{hour12:false})+'</time><span>'+esc(e.message)+'<br><small>'+esc(e.caseId||'데모')+' · '+esc(e.type)+'</small></span></div>').join('')+'</div>':'<p class="ops-muted">실제 접수·분석·승인 시각을 기록합니다.</p>';const m=state.metrics;$('ops-real-timing').textContent=typeof m?.elapsedMsAverage==='number'?'종료 '+m.completedCount+'건 · 평균 '+(m.elapsedMsAverage/1000).toFixed(1)+'초':'실제 경과시간';$('ops-real-timing').title='모든 종료 건의 접수부터 종료까지 실제 경과시간. 모델 추론 시간과는 다른 지표입니다.';}
function renderRoles(){$('ops-integration-list').innerHTML=[['LLM','한국어를 읽는 역할','변경 후보, 원문 인용, 적용 조건, 확인 질문을 실제로 생성'],['검증 코드','후보를 확인하는 역할','원문 근거·수치·날짜·고객 범위·상품 식별자 대조'],['담당자','최종 판단','검증을 통과한 후보의 승인·보류와 예외 처리'],['상품 DB','승인한 결과 보관','SQLite에 원문·분석·검토 이력과 상품 변경을 저장']].map(([n,t,d])=>'<article class="ops-connector"><b>'+n+'</b><span class="local">'+t+'</span><p>'+d+'</p></article>').join('');}
function announceAnalysis(source=$('ops-source').value){analyzing=true;analysisSource=source;analysisError=null;$('ops-analysis-banner').hidden=false;updateMap();$('ops-input-note').textContent='로컬 LLM이 원문을 읽고 있습니다. 응답 후 코드가 검증합니다.';$('ops-ai-detail').innerHTML='<div class="ops-empty ops-thinking"><span>AI</span><h3>실제 모델이 공지를 읽는 중…</h3><p>변경값과 근거 문장을 만드는 데 잠시 걸립니다.</p></div>';$('ops-map').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});}
function switchMode(live){$('ops-workspace').hidden=!live;$('simulation-workspace').hidden=live;for(const [id,active]of[['ops-mode-live',live],['ops-mode-simulation',!live]]){$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active));}}
$('ops-mode-live').addEventListener('click',()=>switchMode(true));$('ops-mode-simulation').addEventListener('click',()=>switchMode(false));
$('ops-map-normal').addEventListener('click',()=>showMapExample('normal'));$('ops-map-held').addEventListener('click',()=>showMapExample('held'));$('ops-map-new').addEventListener('click',()=>action(async()=>{await chooseSample();inputSample.noticeId+='-new-'+crypto.randomUUID();$('ops-notice-label').textContent='새로 분석할 합성 공지';$('ops-compose').open=true;openMapStage('source');}));
$('ops-sample').addEventListener('change',()=>action(async()=>{await chooseSample();$('ops-compose').open=true;resultMessage=null;}));
$('ops-submit').addEventListener('click',()=>action(async()=>{if(!inputSample)throw new Error('샘플 공지를 먼저 준비하세요.');const payload={noticeId:inputSample.noticeId,productId:inputSample.productId,sourceType:inputSample.sourceType,sourceText:$('ops-source').value};announceAnalysis();const result=await api('analyze-notice',payload);selectedId=result.case.id;lastReceipt=structuredClone(payload);oldReview=null;selectedQuote=null;resultMessage={error:false,text:result.duplicate?'같은 원문입니다. 기존 검토 건을 유지했습니다.':'실제 모델의 해석과 코드 검증이 끝났습니다. 근거를 확인하세요.'};$('ops-input-note').textContent='분석 완료. AI 근거 문장을 누르면 원문 위치를 볼 수 있어요.';$('ops-compose').open=false;}));
$('ops-duplicate').addEventListener('click',()=>action(async()=>{if(!lastReceipt)return;const result=await api('analyze-notice',lastReceipt);selectedId=result.case.id;resultMessage={error:false,text:'동일 원문의 재접수입니다. 검토 건을 중복 생성하지 않았습니다.'};}));
$('ops-refresh').addEventListener('click',()=>action(async()=>{await refreshModel();await refresh();resultMessage=null;}));
$('ops-reset').addEventListener('click',()=>action(async()=>{await api('reset',{scope:'synthetic-demo'});selectedId=null;lastReceipt=null;oldReview=null;resultMessage=null;selectedQuote=null;await refresh();await chooseSample();$('ops-input-note').textContent='이 데모의 로컬 합성 기록을 초기화했습니다.';}));
$('ops-export').addEventListener('click',()=>{if(!state)return;const blob=new Blob([JSON.stringify({title:'금융상품 운영실: 실제 LLM 공지 검토',scope:'합성 공지·실제 로컬 실행 기록. 회사 운영 성과 아님.',...state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='financial-product-ops-ai-run.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
action(async()=>{await refresh();await chooseSample();await refreshModel();});
setInterval(async()=>{if(busy||document.hidden||$('ops-workspace').hidden)return;try{await refresh();}catch{$('ops-storage-label').textContent='서버 연결 실패 · 다시 확인하세요';}},5000);
